name: mocktail_exceptions
description: A sample command-line application.
version: 1.0.0
# homepage: https://www.example.com

environment:
  sdk: '>=2.18.5 <3.0.0'

# dependencies:
#   path: ^1.8.0

dev_dependencies:
  build_runner: ^2.3.2
  lints: ^2.0.0
  test: ^1.16.0
dependencies:
  mockito: ^5.3.2
  mocktail: ^0.3.0
