@MinimalAOT_HostAddress = http://localhost:5174

GET {{MinimalAOT_HostAddress}}/todos/
Accept: application/json

###

GET {{MinimalAOT_HostAddress}}/todos/1
Accept: application/json

###

POST {{MinimalAOT_HostAddress}}/todos/
Content-Type: application/json
Accept-Language: en-US,en;q=0.5

{
  "id": 10,
  "title": "wash dishes",
  "isComplete": true
}